const teams = {
    premier: [
        { name: 'AFC Bournemouth' },
        { name: 'Arsenal' },
        { name: 'Aston Villa' },
        { name: 'Brentford' },
        { name: 'Brighton & Hove Albion' },
        { name: 'Chelsea' },
        { name: 'Crystal Palace' },
        { name: 'Everton' },
        { name: 'Fulham' },
        { name: 'Ipswich Town' },
        { name: 'Leicester City' },
        { name: 'Liverpool' },
        { name: 'Manchester City' },
        { name: 'Manchester United' },
        { name: 'Newcastle United' },
        { name: 'Nottingham Forest' },
        { name: 'Southampton' },
        { name: 'Tottenham Hotspur' },
        { name: 'West Ham United' },
        { name: 'Wolverhampton Wanderers' },
    ],
    championship: [
        { name: 'Blackburn Rovers' },
        { name: 'Bristol City' },
        { name: 'Burnley' },
        { name: 'Cardiff City' },
        { name: 'Coventry City' },
        { name: 'Derby County' },
        { name: 'Hull City' },
        { name: 'Leeds United' },
        { name: 'Luton Town' },
        { name: 'Middlesbrough' },
        { name: 'Millwall' },
        { name: 'Norwich City' },
        { name: 'Oxford United' },
        { name: 'Plymouth Argyle' },
        { name: 'Portsmouth' },
        { name: 'Preston North End' },
        { name: 'Queens Park Rangers' },
        { name: 'Sheffield United' },
        { name: 'Sheffield Wednesday' },
        { name: 'Stoke City' },
        { name: 'Sunderland' },
        { name: 'Swansea City' },
        { name: 'Watford' },
        { name: 'West Bromwich Albion' },
    ],
    league1: [
        { name: 'Barnsley' },
        { name: 'Birmingham City' },
        { name: 'Blackpool' },
        { name: 'Bolton Wanderers' },
        { name: 'Bristol Rovers' },
        { name: 'Burton Albion' },
        { name: 'Cambridge United' },
        { name: 'Charlton Athletic' },
        { name: 'Crawley Town' },
        { name: 'Exeter City' },
        { name: 'Huddersfield Town' },
        { name: 'Leyton Orient' },
        { name: 'Lincoln City' },
        { name: 'Mansfield Town' },
        { name: 'Northampton Town' },
        { name: 'Peterborough United' },
        { name: 'Reading' },
        { name: 'Rotherham United' },
        { name: 'Shrewsbury Town' },
        { name: 'Stevenage' },
        { name: 'Stockport County' },
        { name: 'Wigan Athletic' },
        { name: 'Wrexham' },
        { name: 'Wycombe Wanderers' },
    ],
    league2: [
        { name: 'Accrington Stanley' },
        { name: 'AFC Wimbledon' },
        { name: 'Barrow' },
        { name: 'Bradford City' },
        { name: 'Bromley' },
        { name: 'Carlisle United' },
        { name: 'Cheltenham Town' },
        { name: 'Chesterfield' },
        { name: 'Colchester United' },
        { name: 'Crewe Alexander' },
        { name: 'Doncaster Rovers' },
        { name: 'Fleetwood Town' },
        { name: 'Gillingham' },
        { name: 'Grimsby Town' },
        { name: 'Harrogate Town' },
        { name: 'Milton Keynes Dons' },
        { name: 'Morecambe' },
        { name: 'Newport County' },
        { name: 'Notts County' },
        { name: 'Port Vale' },
        { name: 'Salford City' },
        { name: 'Swindon Town' },
        { name: 'Tranmere Rovers' },
        { name: 'Walsall' },
    ],
};

const firstNames = [
    'Alex',
    'Ben',
    'Chris',
    'Dave',
    'Evan',
    'Frank',
    'Gino',
    'Hank',
    'Ivan',
    'Jack',
    'Kevin',
    'Leo',
    'Miles',
    'Ned',
    'Nick',
    'Oli',
    'Patrick',
    'Quinn',
    'Ron',
    'Sam',
    'Trevor',
    'Stan',
    'Vince',
    'Wes',
    'Xander',
    'Zack',
    'Zane',
];

const lastNames = [
    'Smith',
    'Johnson',
    'Brown',
    'Deakin',
    'Taylor',
    'Wilson',
    'Davis',
    'Clark',
    'Lewis',
    'Walker',
    'Hall',
    'Young',
    'King',
    'Wright',
    'Hill',
    'Scott',
    'Green',
];

const nationalities = [
    'England',
    'Spain',
    'Germany',
    'France',
    'Italy',
    'Brazil',
    'Argentina',
    'Portugal',
    'Netherlands',
    'Belgium',
    'Scotland',
    'Wales',
    'Ireland',
    'Sweden',
    'Norway',
];

const formations = [
    { name: '4-4-2', gk: 1, def: 4, mid: 4, fwd: 2 },
    { name: '4-3-3', gk: 1, def: 4, mid: 3, fwd: 3 },
    { name: '3-5-2', gk: 1, def: 3, mid: 5, fwd: 2 },
    { name: '4-2-3-1', gk: 1, def: 4, mid: 5, fwd: 1 },
];
