const teamNames = [
    'Grok United',
    'AI City',
    'Tech Rovers',
    'Code Warriors',
    'Pixel Town',
    'Data Dynamos',
    'Byte Blitz',
    'Circuit Strikers',
    'Nitro FC',
    'Quantum Kickers',
    'Silicon Stars',
    'Gridiron Gurus',
    'Binary Blades',
    'Cyber Celtics',
    'Neon Nomads',
    'Flux Fighters',
    'Pulse Pioneers',
    'Echo Eagles',
    'Vortex Vipers',
    'Spark Spartans',
    'Steel Stingers',
    'Cloud Chasers',
    'Nova Knights',
    'Gizmo Giants',
    'Turbo Titans',
    'Wave Wanderers',
    'Core Crusaders',
    'Pixel Pirates',
    'Tech Tornadoes',
    'Byte Bandits',
    'Circuit Cyclones',
    'Data Dragons',
    'Quantum Quasars',
    'Neon Ninjas',
    'Flux Flyers',
    'Pulse Panthers',
    'Echo Elites',
    'Vortex Victors',
    'Spark Scorpions',
    'Grid Gliders',
    'Iron Ions',
    'Sky Sentinels',
    'Lunar Legends',
    'Code Commanders',
    'Bit Blasters',
    'Wire Wolves',
    'Tech Templars',
    'Nano Navigators',
    'Pulse Prowlers',
    'Echo Enforcers',
    'Vortex Voyagers',
    'Spark Seekers',
    'Grid Guardians',
    'Byte Brawlers',
    'Circuit Chargers',
    'Data Defenders',
    'Quantum Questers',
    'Neon Nomads',
    'Flux Force',
    'Core Captains',
    'Laser Lions',
    'Sonic Stags',
    'Blaze Bears',
    'Thunder Thorns',
    'Frost Falcons',
    'Gale Griffins',
    'Rift Ravens',
    'Tide Titans',
    'Peak Pumas',
    'Crest Cobras',
    'Drift Ducks',
    'Bolt Badgers',
    'Surge Sharks',
    'Glint Gators',
    'Haze Hawks',
    'Void Vultures',
    'Rush Rhinos',
    'Flare Foxes',
    'Chill Cheetahs',
    'Storm Stallions',
    // New teams
    'Magma Mavericks',
    'Cobalt Comets',
    'Prism Phantoms',
    'Aether Archers',
    'Spectral Swords',
    'Dynamo Doves',
    'Zephyr Zebras',
    'Cosmo Cougars',
    'Radiant Rams',
    'Nimbus Navigators',
    'Blitz Beavers',
    'Aurora Avengers',
];
// Rest of file (firstNames, lastNames, etc.) unchanged

const firstNames = [
    'Alex',
    'Ben',
    'Chris',
    'Dave',
    'Evan',
    'Frank',
    'Gino',
    'Hank',
    'Ivan',
    'Jack',
    'Kevin',
    'Leo',
    'Miles',
    'Ned',
    'Oli',
    'Patrick',
    'Quinn',
    'Ron',
    'Sam',
    'Trevor',
    'Stan',
    'Vince',
    'Wes',
    'Xander',
    'Zack',
    'Zane',
];

const lastNames = [
    'Smith',
    'Johnson',
    'Brown',
    'Taylor',
    'Wilson',
    'Davis',
    'Clark',
    'Lewis',
    'Walker',
    'Hall',
    'Young',
    'King',
    'Wright',
    'Hill',
    'Scott',
    'Green',
];

const nationalities = [
    'England',
    'Spain',
    'Germany',
    'France',
    'Italy',
    'Brazil',
    'Argentina',
    'Portugal',
    'Netherlands',
    'Belgium',
    'Scotland',
    'Wales',
    'Ireland',
    'Sweden',
    'Norway',
];

const formations = [
    { name: '4-4-2', gk: 1, def: 4, mid: 4, fwd: 2 },
    { name: '4-3-3', gk: 1, def: 4, mid: 3, fwd: 3 },
    { name: '3-5-2', gk: 1, def: 3, mid: 5, fwd: 2 },
    { name: '4-2-3-1', gk: 1, def: 4, mid: 5, fwd: 1 },
];
